config/routes.rb
Rails.application.routes.draw do
  
  resources :medical_consultations
  resources :tutors
  resources :cities do
    get 'get_cities_by_country', :on => :collection
  end
  resources :countries
  resources :patients do
    get 'search_patient', :on => :collection
  end
  resources :patient_types
  resources :addresses
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users

  root  'welcome#index'

  get   'profile' => 'users#profile', as: :user_profile
  match 'profile' => 'users#update', via: [:put, :patch]

end

app/models/medical_consultation.rb
# encoding: utf-8
class MedicalConsultation < ActiveRecord::Base
  belongs_to :user
  belongs_to :patient

  ANSWER_YES_NO = ["---", "SI", "NO"]

  ANSWER_NATAL = ["Parto", "Cesárea", "Fórcep", "Sencillo", "Gemelar", "Multiple"]

  ANSWER_NATAL_HOSPITABLE = ["Medio hispitalario", "Institucional", "Privado", "Otro"]

  ANSWER_POSTNATAL_FEEDING = ["Seno materno", "Fórmula", "Mixto"]

end

app/helpers/medical_consultations_helper.rb
module MedicalConsultationsHelper
end

app/views/medical_consultations/edit.html.erb
<div class="page-toolbar">
    <div class="page-toolbar-block">
        <h3 class="page-toolbar-title">Editar consulta medica</h3>
        <div class="page-toolbar-subtitle">Editar consulta medica</div>
    </div>
    <div class="page-toolbar-block pull-right">
        <div class="widget-info">
          <div class="btn-group">
            <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to ' Regresar', medical_consultations_path, :class => 'fa fa-reply'  %>
            </li>
          </ul>
          </div>
        </div>
    </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">Inicio</a></li>
      <li class=""> <a href="/medical_consultations">Consultas medicas</a></li>
      <li class="active">Editar registro</li>
    </ol>
  </div>
</div>
<div class="row">
  	<div class="col-md-12">
    	<%= render 'form' %>
   	</div>
</div>

app/views/medical_consultations/index.html.erb
<div class="page-toolbar">
  <div class="page-toolbar-block">
    <h3 class="page-toolbar-title">Consultas medicas</h3>
    <div class="page-toolbar-subtitle">Registros de consultas medicas de pacientes</div>
  </div>  
  <div class="page-toolbar-block pull-right">
    <!-- <div class="widget-info">
      <div class="btn-group">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to ' Nueva consulta medica ', new_medical_consultation_path, :class => 'text-success bg-gray-light fa fa-plus' %>
          </li>
        </ul>
      </div>
    </div>-->
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">Inicio</a></li>
      <li class="active">Consultas medicas</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="block-data table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Paciente</th>
            <th>Creado por</th>
            <th width="200px">Fecha de la consulta</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @medical_consultations.each do |medical_consultation| %>
            <tr>
              <td>
                <% if medical_consultation.patient%>
                  <%= medical_consultation.patient.full_name %>
                <% else %>
                  <i class="text-danger"> No disponible </i>
                <% end %>
              </td>
              <td>
                <% if medical_consultation.user %>
                  <%= medical_consultation.user.first_name %>
                  <%= medical_consultation.user.last_name %>
                <% else %>
                  <i class="text-danger"> No disponible </i>
                <% end %>
              </td>
              <td>
              <%= medical_consultation.updated_at.strftime("%d/%m/%Y | %H:%M %p") %></td>
              <td width="100px"><%= link_to 'Ver detalles', medical_consultation %></td>
              <td width="50px"><%= link_to 'Editar', edit_medical_consultation_path(medical_consultation) %></td>
              <td width="50px">
                <%= form_tag medical_consultation_path(medical_consultation), :class => 'form-delete-data', :method => :delete do %>
                  <a class="text-danger delete-data pointer"> Eliminar </a>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if @medical_consultations.empty? %>
        Aún no hay datos registrados
      <% else %>
        <%= will_paginate @medical_consultations %>
      <% end %>
    </div>
  </div>
</div>

app/views/medical_consultations/new.html.erb
<div class="page-toolbar">
    <div class="page-toolbar-block">
        <h3 class="page-toolbar-title">Nueva consulta medica</h3>
        <div class="page-toolbar-subtitle">Agregar nuevo consulta medica</div>
    </div>
    <div class="page-toolbar-block pull-right">
        <div class="widget-info">
          <div class="btn-group">
            <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to ' Regresar', medical_consultations_path, :class => 'fa fa-reply'  %>
            </li>
          </ul>
          </div>
        </div>
    </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">Inicio</a></li>
      <li class=""> <a href="/medical_consultations">Consultas medicas</a></li>
      <li class="active">Nuevo registro</li>
    </ol>
  </div>
</div>
<div class="row">
  	<div class="col-md-12">
    	<%= render 'form' %>
   	</div>
</div>