config/routes.rb
Rails.application.routes.draw do
  
  resources :medical_consultations
  resources :tutors
  resources :cities do
    get 'get_cities_by_country', :on => :collection
  end
  resources :countries
  resources :patients do
    get 'search_patient', :on => :collection
  end
  resources :patient_types
  resources :addresses
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users

  root  'welcome#index'

  get   'profile' => 'users#profile', as: :user_profile
  match 'profile' => 'users#update', via: [:put, :patch]

end

app/controllers/patient_types_controller.rb
#encoding: utf-8
class PatientTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient_type, only: [:show, :edit, :update, :destroy]

  # GET /patient_types
  # GET /patient_types.json
  def index
    @patient_types = PatientType.paginate(:page => params[:page], :per_page => 15)
  end

  # GET /patient_types/1
  # GET /patient_types/1.json
  def show
  end

  # GET /patient_types/new
  def new
    @patient_type = PatientType.new
  end

  # GET /patient_types/1/edit
  def edit
  end

  # POST /patient_types
  # POST /patient_types.json
  def create
    @patient_type = PatientType.new(patient_type_params)

    respond_to do |format|
      if @patient_type.save
        format.html { redirect_to @patient_type, notice: 'El registro se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @patient_type }
      else
        format.html { render :new }
        format.json { render json: @patient_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_types/1
  # PATCH/PUT /patient_types/1.json
  def update
    respond_to do |format|
      if @patient_type.update(patient_type_params)
        format.html { redirect_to @patient_type, notice: 'El registro se ha actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @patient_type }
      else
        format.html { render :edit }
        format.json { render json: @patient_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_types/1
  # DELETE /patient_types/1.json
  def destroy
    @patient_type.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'El registro fue destruido con éxito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_type
      @patient_type = PatientType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_type_params
      params.require(:patient_type).permit(:name)
    end
end

app/helpers/patient_types_helper.rb
module PatientTypesHelper
end

app/views/patient_types/_form.html.erb
<%= form_for(@patient_type) do |f| %>
  <% if @patient_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient_type.errors.count, "error") %> prohibited this patient_type from being saved:</h2>

      <ul>
      <% @patient_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, 'Nombre' %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="actions">
    <button class="btn btn-success">
      <span class="fa fa-floppy-o"></span> Guardar cambios
    </button>
  </div>
<% end %>

app/views/patient_types/edit.html.erb
<div class="page-toolbar">
  	<div class="page-toolbar-block">
    	<h3 class="page-toolbar-title">Editar tipo de pacinete</h3>
      	<div class="page-toolbar-subtitle">Editar registro de tipo de paciente</div>
  	</div>
  
  	<div class="page-toolbar-block pull-right">
      	<div class="widget-info">
        	<div class="btn-group">
          		<ul class="nav navbar-nav navbar-right">
          			<li>
          				<%= link_to 'Ver detallea', @patient_type %>
          			</li>
            		<li>
              		<%= link_to 'Regresar', patient_types_path, :class => 'text-success' %>
            		</li>
          		</ul>
        	</div>
      	</div>
  	</div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="#">Inicio</a></li>
      <li><a href="/patients">Pacientes</a></li>
      <li><a href="/patient_types">Tipo de pacientes</a></li>
      <li class="active">Editar registro</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="block-data">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/patient_types/index.html.erb
<div class="page-toolbar">
  <div class="page-toolbar-block">
      <h3 class="page-toolbar-title">Tipos de pacientes</h3>
      <div class="page-toolbar-subtitle">Registros de tipos de pacientes</div>
  </div>
  
  <div class="page-toolbar-block pull-right">
      <div class="widget-info">
        <div class="btn-group">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to ' Nuevo tipo de paciente ', new_patient_type_path, :class => 'bg-gray-light  fa fa-plus text-success' %>
            </li>
          </ul>
        </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="#">Inicio</a></li>
      <li><a href="/patients">Pacientes</a></li>
      <li class="active">Tipos de pacientes</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="block-data table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @patient_types.each do |patient_type| %>
            <tr>
              <td><%= patient_type.name %></td>
              <!--<td width="100px"><%= link_to 'Ver detalles', patient_type %></td>-->
              <td width="50px"><%= link_to 'Editar', edit_patient_type_path(patient_type) %></td>
              <td width="50px">

                <%= form_tag patient_type_path(patient_type), :class => 'form-delete-data', :method => :delete do %>
                  <a class="delete-data pointer text-danger"> Eliminar </a>
                <% end %>

              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if @patient_types.empty? %>
        Aún no hay datos registrados
      <% else %>
        <%= will_paginate @patient_types %>
      <% end %>
    </div>
  </div>
</div>

app/views/patient_types/new.html.erb
<div class="page-toolbar">
  <div class="page-toolbar-block">
      <h3 class="page-toolbar-title">Nuevo tipo de paciente</h3>
      <div class="page-toolbar-subtitle">Nuevo registro de tipo de paciente</div>
  </div>
  
  <div class="page-toolbar-block pull-right">
    <div class="widget-info">
      <div class="btn-group">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'Regresar', patient_types_path, :class => 'text-success' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="#">Inicio</a></li>
      <li><a href="/patients">Pacientes</a></li>
      <li><a href="/patient_types">Tipo de pacientes</a></li>
      <li class="active">Nuevo registro</li>
    </ol>
  </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="block-data">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/patient_types/show.html.erb
<div class="page-toolbar">
  	<div class="page-toolbar-block">
    	<h3 class="page-toolbar-title">Tipo de paciente: <b> <%= @patient_type.name %></b></h3>
      	<div class="page-toolbar-subtitle">Registro de tipo de paciente</div>
  	</div>
  
  	<div class="page-toolbar-block pull-right">
      	<div class="widget-info">
        	<div class="btn-group">
          		<ul class="nav navbar-nav navbar-right">
          			<li>
          				<%= link_to ' Editar', edit_patient_type_path(@patient_type), :class => 'bg-gray-light fa fa-pencil' %>
          			</li>
            		<li>
              		<%= link_to ' Regresar', patient_types_path, :class => 'fa fa-reply' %>
            		</li>
          		</ul>
        	</div>
      	</div>
  	</div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="#">Inicio</a></li>
      <li><a href="/patients">Pacientes</a></li>
      <li><a href="/patient_types">Tipo de pacientes</a></li>
      <li class="active">Detalles del registro</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="block-data">
    	<div class="table-responsive">
	      <table class="table table-bordered">
	        <tbody>
	          <tr>
	            <th width="200px">
	              Nombre:
	             </th>
	            <td>
	              <%= @patient_type.name %>
	            </td>
	          </tr>
	        </tbody>
	      </table>
  		</div>
 		</div>
	</div>
</div>