config/routes.rb
Rails.application.routes.draw do
  
  resources :medical_consultations
  resources :tutors
  resources :cities do
    get 'get_cities_by_country', :on => :collection
  end
  resources :countries
  resources :patients do
    get 'search_patient', :on => :collection
  end
  resources :patient_types
  resources :addresses
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users

  root  'welcome#index'

  get   'profile' => 'users#profile', as: :user_profile
  match 'profile' => 'users#update', via: [:put, :patch]

end

app/models/patient.rb
#encoding: utf-8
class Patient < ActiveRecord::Base
  belongs_to :patient_type
  belongs_to :user
  #belongs_to :address
  belongs_to :city
  belongs_to :tutor
  has_many 	:medical_consultation, dependent: :nullify

  GENDER_TYPES = ["Hombre", "Mujer"]

  def full_name
  	"#{first_name} #{last_name}"
  end

  def age

    if birth_date
      years    = Date.today.year.to_i
      months   = Date.today.month.to_i
      days     = Date.today.day.to_i      

      birth_date_year   = birth_date.strftime('%Y').to_i
      birth_date_month  = birth_date.strftime('%m').to_i
      birth_date_day    = birth_date.strftime('%d').to_i

      if birth_date_month > months && birth_date_day > days
        years = years - birth_date_year - 1
      else
        years = years - birth_date_year
      end

      if birth_date_month > months
        months = months + (12 - birth_date_month)
      else
        months = months - birth_date_month
      end

      year_text   = (years > 1 or years == 0) ? "años" : "año"
      month_text  = (months > 1) ? "meses" : "mes"
      day_text    = (days > 1 ) ? "días" : "día"

      "#{years} #{year_text}, #{months} #{month_text} y #{days} #{day_text}"
    else
      "---"
    end
  end

  def type
    if patient_type
      "#{patient_type.name}"
    else
      "---"
    end
  end 

end

app/models/patient_type.rb
class PatientType < ActiveRecord::Base
end

app/controllers/patients_controller.rb
#encoding: utf-8
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  #before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    if params['search']
      search  = params['search']
      @patients = Patient.where("full_name ILIKE ? OR birthplace ILIKE ?","%#{search}%", "%#{search}%").order(last_name: :asc).paginate(:page => params[:page], :per_page => 15)
    else
      @patients = Patient.all.order(last_name: :asc).paginate(:page => params[:page], :per_page => 15)
    end
    #@patients = Patient.all.paginate(:page => params[:page], :per_page => 8)
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @tutors = Tutor.where(patient: @patient.id)
    @medical_consultations = MedicalConsultation::where(patient: @patient.id)
  end

  # GET /patients/new
  def new
    #@tutor          = Tutor.new
    @patient        = Patient.new
    @countries      = Country.all
    @cities         = []#City.all
    @patient_types  = PatientType.all
  end

  # GET /patients/1/edit
  def edit
    @countries      = Country.all
    @cities         = City.where(country_id: @patient.country_id) #country del patient
    @patient_types  = PatientType.all
    @tutors = Tutor.where(patient: @patient.id)
    @medical_consultations = MedicalConsultation::where(patient: @patient.id)

    #if @patient.tutor
    #  @tutor        = Tutor.find(@patient.tutor.id)
    #else
    #  @tutor        = Tutor.new
    #end
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient  = Patient.new(patient_params)
    @patient.full_name = get_full_name

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'El registro se ha creado correctamente' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    @patient.full_name = get_full_name
    
    respond_to do |format|

      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'El registro se ha actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end

      #if @tutor.update(tutor_params)
      #  format.html { redirect_to @patient, notice: 'Patient Tutor was successfully updated.' }
      #  format.json { render :show, status: :ok, location: @patient }
      #else
      #  format.html { render :edit }
      #  format.json { render json: @patient.errors, status: :unprocessable_entity }
      #end

    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'El registro fue destruido con éxito' }
      format.json { head :no_content }
    end
  end

  # GET /alumno_tutors/search_alumno
  def search_patient
    full_name   = params[:full_name] == nil ? '' : params[:full_name]
    @patients     = Patient.where("full_name ILIKE '%#{full_name}%'")
    render "patients/_search_patients", :layout => false
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def get_full_name
      return "#{params[:patient][:first_name]} #{params[:patient][:last_name]}"
    end

    #def set_tutor
    #  @tutor   = Tutor.find(@patient.tutor.id)
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :gender, :city_id, :country_id, :birth_date, :birthplace, :street, :colony, :number, :postal_code,:fiscal_street, :fiscal_colony, :fiscal_number, :fiscal_postal_code, :patient_type_id, :user_id)
    end

    #def tutor_params
    #  params.require(:tutor).permit(:first_name, :last_name, :occupation, :rfc, :phone, :cell_phone)
    #end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient, :html => {:id => "form-patient"}) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-9">
      <div>
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
          <a href="#tab_data_patient" aria-controls="tab_data_patient" role="tab" data-toggle="tab">
          <em class="fa fa-male"></em> Datos del paciente</a>
        </li>
        <li role="presentation">
          <a href="#tab_address_patient" aria-controls="tab_address_patient" role="tab" data-toggle="tab"> <em class="fa fa-map"></em> Dirección del paciente</a>
        </li>
        <li role="presentation">
          <a href="#tab_fiscal_address_patient" aria-controls="tab_fiscal_address_patient" role="tab" data-toggle="tab"> <em class="fa fa-map-o"></em> Dirección fiscal</a>
        </li>
        <% if @patient.id %>
        <li role="presentation">
          <a href="#tab_tutors_patient" aria-controls="tab_tutors_patient" role="tab" data-toggle="tab">
          <em class="fa fa-user"></em> Tutores </a>
        </li>
        <% end %>
        <% if @patient.id %>
        <li role="presentation">
          <a href="#tab_medical_consultation_patient" aria-controls="tab_medical_consultation_patient" role="tab" data-toggle="tab">
          <em class="fa fa-user"></em> Consultas medicas </a>
        </li>
        <% end %>
      </ul>

      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="tab_data_patient">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <th width="200px">
                  <%= f.label :first_name, 'Nombre(s)' %>
                </th>
                <td>
                  <%= f.text_field :first_name, :class => 'form-control' %>
                </td>
              </tr>
              <tr>
                <th>
                  <%= f.label :last_name, 'Apellidos' %>
                </th>
                <td>
                  <%= f.text_field :last_name, :class => 'form-control' %>
                </td>
              </tr>
              <tr>
                <th>
                  <%= f.label :gender, 'Genero' %>
                </th>
                <td>
                  <%= f.select :gender, Patient::GENDER_TYPES, {}, { :class => 'form-control' } %>
                </td>
              </tr>
              <tr>
                <th>
                  <%= f.label :birth_date, 'Fecha de nacimiento' %>
                </th>
                <td>
                  <%= f.date_select :birth_date, :start_year => 1900, :end_year => Date.today.year,  :html => { :class => '' } %>
                </td>
              </tr>
              <tr>
                <th>
                  <%= f.label :birthplace, 'Lugar de nacimiento' %>
                </th>
                <td>
                  <%= f.text_area :birthplace, :class => 'form-control' %>
                </td>
              </tr>
              <tr>
                <th>
                  <%= f.label :patient_type_id, 'Tipo de paciente' %>
                </th>
                <td>
                  <%= f.select :patient_type_id, options_for_select(@patient_types.collect { |type|
            [type.name.titleize, type.id] }, 1), {}, { id: 'patient_type_select', :class => 'form-control' } %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="tab_address_patient">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <th width="200px">
                    <%= f.label :street, 'Calle' %>
                  </th>
                  <td>
                    <%= f.text_field :street, :class => 'form-control' %>
                  </td>
                </tr>
                <tr>
                  <th>
                    <%= f.label :number, 'Numero (Int. y Ext.)' %>
                  </th>
                  <td>
                    <%= f.text_field :number, :class => 'form-control' %>
                  </td>
                </tr>
                <tr>
                  <th>
                    <%= f.label :colony, 'Colonia' %>
                  </th>
                  <td>
                    <%= f.text_field :colony, :class => 'form-control' %>
                  </td>
                </tr>
                <tr>
                  <th>
                    <%= f.label :postal_code, 'Código postal' %>
                  </th>
                  <td>
                    <%= f.text_field :postal_code, :class => 'form-control' %>
                  </td>
                </tr>
                <!--<tr>
                  <th>
                    <%= f.label :country_id, 'Estado' %>
                  </th>
                  <td>
                    <%= f.select :country_id, options_for_select(@countries.collect{ |u| [u.name, u.id] }, @patient.country_id), {:include_blank => '--- Seleccionar ---'},{ id: 'country_id', :class => 'form-control' } %>
                  </td>
                </tr>

                <tr>
                  <th>
                    <%= f.label :city_id, 'Ciudad' %>
                  </th>
                  <td>
                    <%= f.select :city_id, options_for_select(@cities.collect{ |u| [u.name, u.id] }, @patient.city_id), {}, { id: 'citites_select', :class => 'form-control' } %>
                  </td>
                </tr>
                -->
              </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="tab_fiscal_address_patient">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <th width="200px">
                    <%= f.label :fiscal_street, 'Calle' %>
                  </th>
                  <td>
                    <%= f.text_field :fiscal_street, :class => 'form-control' %>
                  </td>
                </tr>
                <tr>
                  <th>
                    <%= f.label :fiscal_number, 'Numero (Int. y Ext.)' %>
                  </th>
                  <td>
                    <%= f.text_field :fiscal_number, :class => 'form-control' %>
                  </td>
                </tr>
                <tr>
                  <th>
                    <%= f.label :fiscal_colony, 'Colonia' %>
                  </th>
                  <td>
                    <%= f.text_field :fiscal_colony, :class => 'form-control' %>
                  </td>
                </tr>
                <tr>
                  <th>
                    <%= f.label :fiscal_postal_code, 'Código postal' %>
                  </th>
                  <td>
                    <%= f.text_field :fiscal_postal_code, :class => 'form-control' %>
                  </td>
                </tr>
              </tbody>
            </table>
        </div>
        <% if @patient.id %>
        <div role="tabpanel" class="tab-pane" id="tab_tutors_patient">
          <div class="well">
          <div class="panel" align="right">
            <%= link_to ' Agregar nuevo tutor', new_tutor_path(:patient_id => @patient.id), :class => 'fa fa-plus' %>
          </div>
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead>
                <th>Nombre</th>
                <th>RFC</th>
                <th>Teléfono</th>
                <th>Teléfono celular</th>
                <th colspan="2"></th>
              </thead>
              <tbody>
              <% @tutors.each do |tutor| %>
                <tr>
                  <td>
                    <%= tutor.first_name %> <%= tutor.last_name %>
                  </td>
                  <td>
                    <%= tutor.rfc %>
                  </td>
                  <td>
                    <%= tutor.phone %>
                  </td>
                  <td>
                    <%= tutor.cell_phone %>
                  </td>
                  <td><%= link_to 'Editar', edit_tutor_path(tutor, :patient_id => @patient.id) %></td>
                  
                </tr>
              </tbody>
              <% end %>
            </table>
            <% if @tutors.empty? %>
              <i class="text-danger">Sin registo</i>
            <% end %>
          </div>
          </div>
        </div>
        <% end %>
        
        <% if @patient.id %>
          <div role="tabpanel" class="tab-pane" id="tab_medical_consultation_patient">
            <div class="well">
              <div class="panel" align="right">
              <%= link_to ' Nueva consulta medica ', new_medical_consultation_path(:patient_id => @patient.id), :class => 'fa fa-plus' %>
              </div>
              <table class="table table-bordered">
                <thead>
                  <th>Creado por</th>
                  <th width="200px">Fecha de la consulta</th>
                  <th colspan="3"></th>
                </thead>
                <tbody>
                  <% @medical_consultations.each do |medical_consultation| %>
                    <tr>
                      <td>
                        <% if medical_consultation.user %>
                          <%= medical_consultation.user.first_name %>
                          <%= medical_consultation.user.last_name %>
                        <% else %>
                          <i class="text-danger"> No disponible </i>
                        <% end %>
                      </td>
                      <td><%= medical_consultation.updated_at.strftime("%d/%m/%Y | %H:%M %p") %></td>
                      <td width="100px"><%= link_to 'Ver detalles', medical_consultation %></td>
                      <td width="50px"><%= link_to 'Editar', edit_medical_consultation_path(medical_consultation) %>
                      </td>
                      
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <% if @medical_consultations.empty? %>
                <i class="text-danger">Sin registo</i>
              <% end %>
            </div>
          </div>
          <% end %>
      </div>
    </div>
      <!---<div class="field">
        <%= f.label :user_id %><br>
        <%= f.text_field :user_id %>
      </div>-->
    </div>
    <div class="col-md-3">
      <div class="well mt40">
        <div class="actions">
          <button class="btn btn-success btn-block">
            <span class="fa fa-floppy-o"></span> Guardar cambios
          </button>
        </div>
      </div>
    </div>  
  </div>
</div>
  
<% end %>

app/views/patients/edit.html.erb
<div class="page-toolbar">
    <div class="page-toolbar-block">
        <h3 class="page-toolbar-title">Editar paciente</h3>
        <div class="page-toolbar-subtitle">Actualizando información del paciente</div>
    </div>
    <div class="page-toolbar-block pull-right">
        <div class="widget-info">
          <div class="btn-group">
            <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Ver detalles', @patient %> 
            </li>
            <li>
              <%= link_to ' Regresar', patients_path, :class => 'fa fa-reply' %>
            </li>
          </ul>
          </div>
        </div>
    </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">Inicio</a></li>
      <li class=""> <a href="/patients">Pacientes</a></li>
      <li class="active">Editar registro</li>
    </ol>
  </div>
</div>
<div class="row">
  	<div class="col-md-12">
    	<div class="block-data">
    		<%= render 'form' %>
    	</div>
    </div>
</div>

app/views/patients/index.html.erb
<div class="page-toolbar">
  <div class="page-toolbar-block">
    <h3 class="page-toolbar-title">Pacientes</h3>
    <div class="page-toolbar-subtitle">Registros de pacientes</div>
  </div>
  <div class="page-toolbar-block pull-right">
    <div class="widget-info">
      <div class="btn-group">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to ' Nuevo paciente ', new_patient_path, :class => 'text-success bg-gray-light fa fa-plus' %>
          </li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Más acciones
              <span class="fa fa-caret-down"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<%= patient_types_path() %>">Tipo de pacientes</a></li>
               <!--<li>
                <%= link_to 'Estados (Dirección)', countries_path, :class => 'text-success' %>
              </li>
              <li>
                <%= link_to 'Ciudades (Dirección)', cities_path, :class => 'text-success' %>
              </li>-->
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <ol class="breadcrumb">
      <li><a href="/">Inicio</a></li>
      <li class="active">Pacientes</li>
    </ol>
  </div>
  <div class="col-md-4">
    <form>
      <div class="input-group">
        <input type="text" name="search" value="<%= params['search'] %>" class="form-control" placeholder="Nombre completo">
        <span class="input-group-btn">
          <input type="submit" class="btn btn-primary" value="Buscar">
        </span>
      </div>
    </form>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="block-data table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre completo</th>
            <th>Tipo de paciente</th>
            <th>Consulta medica</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @patients.each do |patient| %>
            <tr>
              <td width="400px"><%= patient.last_name %> <%= patient.first_name %></td>
              <td width="200px"><%= patient.patient_type != nil ? patient.patient_type.name : '' %></td>
              <td width="200px">
                <%= link_to ' Nueva consulta medica ', new_medical_consultation_path(:patient_id => patient.id), :class => 'text-success fa fa-plus' %>
              </td>
              <td width="100px">
                <%= link_to 'Ver detalles', patient, :class => '' %>
              </td>
              <td width="50px">
                <%= link_to 'Editar', edit_patient_path(patient),:class => '' %>
              </td>
              <td width="50px">
                <%= form_tag patient_path(patient), :class => 'form-delete-data', :method => :delete do %>
                  <a class="delete-data pointer text-danger"> Eliminar </a>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if @patients.empty? %>
        Aún no hay datos registrados
      <% else %>
        <%= will_paginate @patients %>
      <% end %>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class="page-toolbar">
    <div class="page-toolbar-block">
        <h3 class="page-toolbar-title">Nuevo paciente</h3>
        <div class="page-toolbar-subtitle">Agregar nuevo paciente</div>
    </div>
    <div class="page-toolbar-block pull-right">
        <div class="widget-info">
          <div class="btn-group">
            <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Regresar', patients_path %>
            </li>
          </ul>
          </div>
        </div>
    </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">Inicio</a></li>
      <li class=""> <a href="/patients">Pacientes</a></li>
      <li class="active">Nuevo registro</li>
    </ol>
  </div>
</div>
<div class="row">
  	<div class="col-md-12">
    	<div class="block-data">
    		<%= render 'form' %>
    	</div>
   	</div>
</div>

app/views/patients/show.html.erb
<div class="page-toolbar">
  <div class="page-toolbar-block">
      <h3 class="page-toolbar-title">Paciente: <b> <%= @patient.full_name %></b></h3>
      <div class="page-toolbar-subtitle">Detalles del paciente</div>
  </div>
  <div class="page-toolbar-block pull-right">
      <div class="widget-info">
        <div class="btn-group">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to ' Nueva consulta medica ', new_medical_consultation_path(:patient_id => @patient.id), :class => 'fa fa-plus' %>
            </li>
            <li>
              <%= link_to ' Editar ', edit_patient_path(@patient), :class => 'bg-gray-light fa fa-pencil'  %>
            </li>
            <li>
              <%= link_to ' Regresar', patients_path, :class => 'fa fa-reply' %>
            </li>
          </ul>
        </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">Inicio</a></li>
      <li class=""> <a href="/patients">Pacientes</a></li>
      <li class="active">Detalles del registro</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="block-data">
      <div class="table-responsive">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#tab_data_patient" aria-controls="tab_data_patient" role="tab" data-toggle="tab">
              <em class="fa fa-male"></em> Datos del paciente
            </a>
          </li>
          <li role="presentation">
            <a href="#tab_tutors_patient" aria-controls="tab_tutors_patient" role="tab" data-toggle="tab"> <em class="fa fa-user"></em> Tutores</a>
          </li>
          <li role="presentation">
            <a href="#tab_tutors_medical_consultations" aria-controls="tab_tutors_medical_consultations" role="tab" data-toggle="tab"> <em class="fa fa-stethoscope"></em> Consultas medicas</a>
          </li>
        </ul>

        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="tab_data_patient">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <th width="200px">
                    Paciente:
                  </th>
                  <td>
                    <%= @patient.full_name %>
                  </td>
                </tr>
                <tr>
                  <th width="200px">
                    Genero:
                  </th>
                  <td>
                    <%= @patient.gender %>
                  </td>
                </tr>
                <tr>
                  <th>
                    Fecha de nacimiento:
                  </th>
                  <td>
                    <%= @patient.birth_date %>
                  </td>
                </tr>
                <tr>
                  <th>
                    Edad:
                  </th>
                  <td>
                    <%= @patient.age %>
                  </td>
                </tr>
                <tr>
                  <th>
                    Lugar de nacimiento:
                  </th>
                  <td>
                    <%= @patient.birthplace %>
                  </td>
                </tr>
                <tr>
                  <th>
                    Tipo de paciente:
                  </th>
                  <td>
                    <%= @patient.patient_type != nil ? @patient.patient_type.name : '' %>
                  </td>
                </tr>
              </tbody>
            </table>
            
            <table class="table table-bordered">
              <tbody>
                  <tr>
                    <th width="200px">
                      Dirección del paciente:
                    </th>
                    <td>
                      <%= @patient.street %>
                      <%= @patient.number %>
                      <%= @patient.colony %>
                      <%= @patient.postal_code %>
                    </td>
                  </tr>
              </tbody>
            </table>

            <table class="table table-bordered">
              <tbody>
                  <tr>
                    <th width="200px">
                      Dirección fiscal:
                    </th>
                    <td>
                      <%= @patient.fiscal_street %>
                      <%= @patient.fiscal_number %>
                      <%= @patient.fiscal_colony %>
                      <%= @patient.fiscal_postal_code %>
                    </td>
                  </tr>
              </tbody>
            </table>

          </div>
          <div role="tabpanel" class="tab-pane" id="tab_tutors_patient">
            <div class="well">
            <div class="panel" align="right">
              <%= link_to ' Agregar nuevo tutor', new_tutor_path(:patient_id => @patient.id), :class => 'fa fa-plus' %>
            </div>
            <table class="table table-bordered">
              <thead>
                <th>Nombre</th>
                <th>RFC</th>
                <th>Teléfono</th>
                <th>Teléfono celular</th>
                <th colspan="2"></th>
              </thead>
              <tbody>
              <% @tutors.each do |tutor| %>
                <tr>
                  <td>
                    <%= tutor.first_name %> <%= tutor.last_name %>
                  </td>
                  <td>
                    <%= tutor.rfc %>
                  </td>
                  <td>
                    <%= tutor.phone %>
                  </td>
                  <td>
                    <%= tutor.cell_phone %>
                  </td>
                  <td><%= link_to 'Editar', edit_tutor_path(tutor, :patient_id => @patient.id) %></td>
                  <td width="50px">
                    <%= form_tag tutor_path(tutor, :patient_id => @patient.id), :class => 'form-delete-data', :method => :delete do %>
                      <a class="delete-data pointer text-danger"> Eliminar </a>
                    <% end %>
                  </td>
                </tr>
              </tbody>
              <% end %>
            </table>
            <% if @tutors.empty? %>
              <i class="text-danger">Sin registo</i>
            <% end %>
          </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="tab_tutors_medical_consultations">
            <div class="well">
              <div class="panel" align="right">
              <%= link_to ' Nueva consulta medica ', new_medical_consultation_path(:patient_id => @patient.id), :class => 'fa fa-plus' %>
              </div>
              <table class="table table-bordered">
                <thead>
                  <th>Creado por</th>
                  <th width="200px">Fecha de la consulta</th>
                  <th colspan="3"></th>
                </thead>
                <tbody>
                  <% @medical_consultations.each do |medical_consultation| %>
                    <tr>
                      <td>
                        <% if medical_consultation.user %>
                          <%= medical_consultation.user.first_name %>
                          <%= medical_consultation.user.last_name %>
                        <% else %>
                          <i class="text-danger"> No disponible </i>
                        <% end %>
                      </td>
                      <td><%= medical_consultation.updated_at.strftime("%d/%m/%Y | %H:%M %p") %></td>
                      <td width="100px"><%= link_to 'Ver detalles', medical_consultation %></td>
                      <td width="50px"><%= link_to 'Editar', edit_medical_consultation_path(medical_consultation) %>
                      </td>
                      <td width="50px">
                      <%= form_tag medical_consultation_path(medical_consultation), :class => 'form-delete-data', :method => :delete do %>
                        <a class="delete-data pointer text-danger"> Eliminar </a>
                      <% end %>
                    </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <% if @medical_consultations.empty? %>
                <i class="text-danger">Sin registo</i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>