config/routes.rb
Rails.application.routes.draw do
  
  resources :medical_consultations
  resources :tutors
  resources :cities do
    get 'get_cities_by_country', :on => :collection
  end
  resources :countries
  resources :patients do
    get 'search_patient', :on => :collection
  end
  resources :patient_types
  resources :addresses
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users

  root  'welcome#index'

  get   'profile' => 'users#profile', as: :user_profile
  match 'profile' => 'users#update', via: [:put, :patch]

end

app/controllers/addresses_controller.rb
#encoding: utf-8
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'El registro se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'El registro se ha actualizado correctamente' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'El registro fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :number, :colony, :city_id, :postal_code)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :colony %><br>
    <%= f.text_field :colony %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.text_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<div class="page-toolbar">
    <div class="page-toolbar-block">
        <h3 class="page-toolbar-title">Direcciones</h3>
        <div class="page-toolbar-subtitle">Registros de direccionde de los pacientes</div>
    </div>
    
    <div class="page-toolbar-block pull-right">
        <div class="widget-info">
          <div class="btn-group">
            <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Nuevo', new_address_path, :class => 'text-success' %>
            </li>
             <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Más acciones
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Estados', countries_path, :class => 'text-success' %>
                </li>
                <li>
                  <%= link_to 'Ciudades', cities_path, :class => 'text-success' %>
                </li>
              </ul>
            </li>
          </ul>
          </div>
        </div>
    </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="block-data table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Dirección</th>
            <th>Ciudad y Estado</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @addresses.each do |address| %>
            <tr>
              <td><%= address.street %>
                  <%= address.number %>
                  <%= address.postal_code %>
              </td>
              <td><%= address.city %></td>
              <td width="100px"><%= link_to 'Ver detalles', address %></td>
              <td><%= link_to 'Editar', edit_address_path(address) %></td>
              <td><%= link_to 'Eliminar', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @address.number %>
</p>

<p>
  <strong>Colony:</strong>
  <%= @address.colony %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @address.postal_code %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>